[atom]
id = "nixpkgs-atom"
version = "0.1.0"

[features]
default = ["system"]

[fetch.nixpkgs]
name = "nixpkgs"
type = "import"

[fetch.lib]
name = "nixpkgs"
type = "import"
subdir = "lib"

[fetch.nixos-lib]
name = "nixpkgs"
type = "import"
subdir = "nixos/lib"

[backend.nix]
fetcher = "npins"